create table if not exists public.horarios_temples (
  id text primary key,
  name text not null,
  city text not null,
  province text not null,
  address text not null,
  lat double precision not null,
  lng double precision not null,
  status text not null default 'review',
  contact_phone text,
  contact_whatsapp text,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.horarios_temples
  drop constraint if exists horarios_temples_status_check;

alter table public.horarios_temples
  add constraint horarios_temples_status_check
  check (status in ('updated', 'review', 'stale'));

create table if not exists public.horarios_celebrations (
  id text primary key,
  temple_id text not null references public.horarios_temples(id) on delete cascade,
  type text not null,
  weekday text not null,
  start_time time not null,
  duration_min integer not null,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.horarios_celebrations
  drop constraint if exists horarios_celebrations_type_check;

alter table public.horarios_celebrations
  add constraint horarios_celebrations_type_check
  check (type in ('misa', 'adoracion', 'confesion', 'rosario', 'liturgia'));

alter table public.horarios_celebrations
  drop constraint if exists horarios_celebrations_weekday_check;

alter table public.horarios_celebrations
  add constraint horarios_celebrations_weekday_check
  check (weekday in ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'));

alter table public.horarios_celebrations
  drop constraint if exists horarios_celebrations_duration_check;

alter table public.horarios_celebrations
  add constraint horarios_celebrations_duration_check
  check (duration_min > 0 and duration_min <= 240);

create table if not exists public.horarios_search_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  query text not null default '',
  city text,
  celebration_type text,
  time_range text,
  sort text not null default 'relevance',
  results_count integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.horarios_search_events
  drop constraint if exists horarios_search_events_type_check;

alter table public.horarios_search_events
  add constraint horarios_search_events_type_check
  check (
    celebration_type is null
    or celebration_type in ('misa', 'adoracion', 'confesion', 'rosario', 'liturgia')
  );

alter table public.horarios_search_events
  drop constraint if exists horarios_search_events_range_check;

alter table public.horarios_search_events
  add constraint horarios_search_events_range_check
  check (time_range is null or time_range in ('morning', 'afternoon', 'evening'));

alter table public.horarios_search_events
  drop constraint if exists horarios_search_events_sort_check;

alter table public.horarios_search_events
  add constraint horarios_search_events_sort_check
  check (sort in ('relevance', 'nearby', 'soonest'));

create index if not exists idx_horarios_temples_city_name
  on public.horarios_temples(city, name);

create index if not exists idx_horarios_temples_status
  on public.horarios_temples(status);

create index if not exists idx_horarios_celebrations_temple
  on public.horarios_celebrations(temple_id);

create index if not exists idx_horarios_celebrations_weekday_time
  on public.horarios_celebrations(weekday, start_time);

create index if not exists idx_horarios_celebrations_type_active
  on public.horarios_celebrations(type, is_active)
  where is_active = true;

create index if not exists idx_horarios_search_events_created
  on public.horarios_search_events(created_at desc);

create index if not exists idx_horarios_search_events_session
  on public.horarios_search_events(session_id, created_at desc);

alter table public.horarios_temples enable row level security;
alter table public.horarios_celebrations enable row level security;
alter table public.horarios_search_events enable row level security;

drop policy if exists horarios_temples_read_public on public.horarios_temples;
create policy horarios_temples_read_public
on public.horarios_temples
for select
to anon, authenticated
using (true);

drop policy if exists horarios_temples_service_role_write on public.horarios_temples;
create policy horarios_temples_service_role_write
on public.horarios_temples
for all
to service_role
using (true)
with check (true);

drop policy if exists horarios_celebrations_read_public on public.horarios_celebrations;
create policy horarios_celebrations_read_public
on public.horarios_celebrations
for select
to anon, authenticated
using (is_active = true);

drop policy if exists horarios_celebrations_service_role_write on public.horarios_celebrations;
create policy horarios_celebrations_service_role_write
on public.horarios_celebrations
for all
to service_role
using (true)
with check (true);

drop policy if exists horarios_search_events_insert_public on public.horarios_search_events;
create policy horarios_search_events_insert_public
on public.horarios_search_events
for insert
to anon, authenticated
with check (results_count >= 0 and results_count <= 2000);

drop policy if exists horarios_search_events_service_role_read on public.horarios_search_events;
create policy horarios_search_events_service_role_read
on public.horarios_search_events
for select
to service_role
using (true);

drop policy if exists horarios_search_events_service_role_write on public.horarios_search_events;
create policy horarios_search_events_service_role_write
on public.horarios_search_events
for all
to service_role
using (true)
with check (true);

grant select on public.horarios_temples to anon, authenticated;
grant select on public.horarios_celebrations to anon, authenticated;
grant insert on public.horarios_search_events to anon, authenticated;

grant all privileges on public.horarios_temples to service_role;
grant all privileges on public.horarios_celebrations to service_role;
grant all privileges on public.horarios_search_events to service_role;
grant usage, select on sequence public.horarios_search_events_id_seq to service_role;

insert into public.horarios_temples (
  id,
  name,
  city,
  province,
  address,
  lat,
  lng,
  status,
  contact_phone,
  contact_whatsapp,
  notes
)
values
  ('santa-teresita-parana', 'Parroquia Santa Teresita', 'Parana', 'Entre Rios', 'Av. Almafuerte 420, Parana', -31.7424, -60.5238, 'updated', '+54 343 412-0045', '+54 343 470-8954', 'Confesiones 30 minutos antes de Misa vespertina.'),
  ('catedral-parana', 'Catedral Nuestra Senora del Rosario', 'Parana', 'Entre Rios', 'Su Santidad Francisco 57, Parana', -31.7317, -60.5235, 'updated', '+54 343 423-0181', null, 'Misa dominical central con coro arquidiocesano.'),
  ('sagrado-corazon-parana', 'Capilla Sagrado Corazon', 'Parana', 'Entre Rios', 'Calle Nogoya 1330, Parana', -31.7481, -60.5077, 'review', '+54 343 421-5531', null, 'Horario sujeto a confirmacion semanal.'),
  ('san-jose-orero-sfe', 'Parroquia San Jose Obrero', 'Santa Fe', 'Santa Fe', 'J. M. Zuviria 3050, Santa Fe', -31.6408, -60.7001, 'updated', '+54 342 456-0021', null, null),
  ('basilica-guadalupe-sfe', 'Basilica de Guadalupe', 'Santa Fe', 'Santa Fe', 'Javier de la Rosa 623, Santa Fe', -31.6132, -60.6729, 'updated', '+54 342 460-1111', null, null),
  ('san-miguel-cordoba', 'Parroquia San Miguel Arcangel', 'Cordoba', 'Cordoba', 'Av. Colon 812, Cordoba', -31.4166, -64.1888, 'stale', '+54 351 434-2200', null, 'Ultima actualizacion reportada hace mas de 30 dias.'),
  ('santa-rita-cordoba', 'Parroquia Santa Rita', 'Cordoba', 'Cordoba', 'Juan B. Justo 2470, Cordoba', -31.4014, -64.1674, 'review', '+54 351 475-9090', null, null),
  ('nuestra-senora-pilar-rosario', 'Parroquia Nuestra Senora del Pilar', 'Rosario', 'Santa Fe', 'Cordoba 1420, Rosario', -32.9478, -60.6393, 'updated', '+54 341 429-7155', null, null),
  ('san-cayetano-rosario', 'Parroquia San Cayetano', 'Rosario', 'Santa Fe', 'Buenos Aires 2150, Rosario', -32.9608, -60.6428, 'updated', '+54 341 486-4450', null, null),
  ('cristo-redentor-buenos-aires', 'Parroquia Cristo Redentor', 'Buenos Aires', 'Buenos Aires', 'Av. Rivadavia 4800, CABA', -34.6155, -58.4328, 'review', '+54 11 4124-8800', null, null),
  ('san-benito-buenos-aires', 'Parroquia San Benito Abad', 'Buenos Aires', 'Buenos Aires', 'Maure 920, CABA', -34.5741, -58.4381, 'updated', '+54 11 4777-7397', null, null),
  ('san-vicente-mendoza', 'Parroquia San Vicente Ferrer', 'Mendoza', 'Mendoza', 'Belgrano 240, Mendoza', -32.8898, -68.8454, 'stale', '+54 261 423-7720', null, null)
on conflict (id) do update
set
  name = excluded.name,
  city = excluded.city,
  province = excluded.province,
  address = excluded.address,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status,
  contact_phone = excluded.contact_phone,
  contact_whatsapp = excluded.contact_whatsapp,
  notes = excluded.notes,
  updated_at = timezone('utc', now());

insert into public.horarios_celebrations (
  id,
  temple_id,
  type,
  weekday,
  start_time,
  duration_min,
  notes,
  is_active
)
values
  ('stp-monday-1900', 'santa-teresita-parana', 'misa', 'monday', '19:00', 50, null, true),
  ('stp-tuesday-1900', 'santa-teresita-parana', 'misa', 'tuesday', '19:00', 50, null, true),
  ('stp-wednesday-1900', 'santa-teresita-parana', 'misa', 'wednesday', '19:00', 50, null, true),
  ('stp-thursday-1900', 'santa-teresita-parana', 'misa', 'thursday', '19:00', 50, null, true),
  ('stp-friday-1900', 'santa-teresita-parana', 'misa', 'friday', '19:00', 50, null, true),
  ('stp-saturday-1930', 'santa-teresita-parana', 'misa', 'saturday', '19:30', 55, null, true),
  ('stp-sunday-0930', 'santa-teresita-parana', 'misa', 'sunday', '09:30', 60, null, true),
  ('stp-sunday-2000', 'santa-teresita-parana', 'misa', 'sunday', '20:00', 60, null, true),
  ('stp-thursday-1800', 'santa-teresita-parana', 'adoracion', 'thursday', '18:00', 45, null, true),
  ('stp-saturday-1830', 'santa-teresita-parana', 'confesion', 'saturday', '18:30', 40, null, true),
  ('cat-monday-1830', 'catedral-parana', 'misa', 'monday', '18:30', 50, null, true),
  ('cat-tuesday-1830', 'catedral-parana', 'misa', 'tuesday', '18:30', 50, null, true),
  ('cat-wednesday-1830', 'catedral-parana', 'misa', 'wednesday', '18:30', 50, null, true),
  ('cat-thursday-1830', 'catedral-parana', 'misa', 'thursday', '18:30', 50, null, true),
  ('cat-friday-1830', 'catedral-parana', 'misa', 'friday', '18:30', 50, null, true),
  ('cat-sunday-1030', 'catedral-parana', 'misa', 'sunday', '10:30', 65, null, true),
  ('cat-sunday-1900', 'catedral-parana', 'misa', 'sunday', '19:00', 65, null, true),
  ('scr-sunday-1100', 'sagrado-corazon-parana', 'misa', 'sunday', '11:00', 55, null, true),
  ('scr-friday-1800', 'sagrado-corazon-parana', 'rosario', 'friday', '18:00', 35, null, true),
  ('sjo-monday-1900', 'san-jose-orero-sfe', 'misa', 'monday', '19:00', 55, null, true),
  ('sjo-tuesday-1900', 'san-jose-orero-sfe', 'misa', 'tuesday', '19:00', 55, null, true),
  ('sjo-wednesday-1900', 'san-jose-orero-sfe', 'misa', 'wednesday', '19:00', 55, null, true),
  ('sjo-thursday-1900', 'san-jose-orero-sfe', 'misa', 'thursday', '19:00', 55, null, true),
  ('sjo-friday-1900', 'san-jose-orero-sfe', 'misa', 'friday', '19:00', 55, null, true),
  ('sjo-saturday-1930', 'san-jose-orero-sfe', 'misa', 'saturday', '19:30', 60, null, true),
  ('sjo-sunday-0900', 'san-jose-orero-sfe', 'misa', 'sunday', '09:00', 65, null, true),
  ('sjo-sunday-2000', 'san-jose-orero-sfe', 'misa', 'sunday', '20:00', 65, null, true),
  ('bgs-sunday-1030', 'basilica-guadalupe-sfe', 'misa', 'sunday', '10:30', 65, null, true),
  ('bgs-sunday-1900', 'basilica-guadalupe-sfe', 'misa', 'sunday', '19:00', 65, null, true),
  ('bgs-saturday-1730', 'basilica-guadalupe-sfe', 'confesion', 'saturday', '17:30', 45, null, true),
  ('smc-sunday-1100', 'san-miguel-cordoba', 'misa', 'sunday', '11:00', 55, null, true),
  ('smc-wednesday-1930', 'san-miguel-cordoba', 'misa', 'wednesday', '19:30', 55, null, true),
  ('srt-sunday-0930', 'santa-rita-cordoba', 'misa', 'sunday', '09:30', 55, null, true),
  ('srt-sunday-1930', 'santa-rita-cordoba', 'misa', 'sunday', '19:30', 55, null, true),
  ('srt-thursday-1800', 'santa-rita-cordoba', 'adoracion', 'thursday', '18:00', 45, null, true),
  ('nsp-monday-1900', 'nuestra-senora-pilar-rosario', 'misa', 'monday', '19:00', 50, null, true),
  ('nsp-tuesday-1900', 'nuestra-senora-pilar-rosario', 'misa', 'tuesday', '19:00', 50, null, true),
  ('nsp-wednesday-1900', 'nuestra-senora-pilar-rosario', 'misa', 'wednesday', '19:00', 50, null, true),
  ('nsp-thursday-1900', 'nuestra-senora-pilar-rosario', 'misa', 'thursday', '19:00', 50, null, true),
  ('nsp-friday-1900', 'nuestra-senora-pilar-rosario', 'misa', 'friday', '19:00', 50, null, true),
  ('nsp-sunday-1000', 'nuestra-senora-pilar-rosario', 'misa', 'sunday', '10:00', 60, null, true),
  ('nsp-sunday-2000', 'nuestra-senora-pilar-rosario', 'misa', 'sunday', '20:00', 60, null, true),
  ('sca-saturday-1900', 'san-cayetano-rosario', 'misa', 'saturday', '19:00', 55, null, true),
  ('sca-sunday-1030', 'san-cayetano-rosario', 'misa', 'sunday', '10:30', 60, null, true),
  ('sca-friday-1830', 'san-cayetano-rosario', 'rosario', 'friday', '18:30', 35, null, true),
  ('crb-sunday-1100', 'cristo-redentor-buenos-aires', 'misa', 'sunday', '11:00', 60, null, true),
  ('crb-sunday-2000', 'cristo-redentor-buenos-aires', 'misa', 'sunday', '20:00', 60, null, true),
  ('crb-thursday-1830', 'cristo-redentor-buenos-aires', 'liturgia', 'thursday', '18:30', 45, null, true),
  ('sbb-monday-1830', 'san-benito-buenos-aires', 'misa', 'monday', '18:30', 50, null, true),
  ('sbb-tuesday-1830', 'san-benito-buenos-aires', 'misa', 'tuesday', '18:30', 50, null, true),
  ('sbb-wednesday-1830', 'san-benito-buenos-aires', 'misa', 'wednesday', '18:30', 50, null, true),
  ('sbb-thursday-1830', 'san-benito-buenos-aires', 'misa', 'thursday', '18:30', 50, null, true),
  ('sbb-friday-1830', 'san-benito-buenos-aires', 'misa', 'friday', '18:30', 50, null, true),
  ('sbb-sunday-1000', 'san-benito-buenos-aires', 'misa', 'sunday', '10:00', 60, null, true),
  ('sbb-sunday-1900', 'san-benito-buenos-aires', 'misa', 'sunday', '19:00', 60, null, true),
  ('svm-sunday-0930', 'san-vicente-mendoza', 'misa', 'sunday', '09:30', 55, null, true),
  ('svm-sunday-1930', 'san-vicente-mendoza', 'misa', 'sunday', '19:30', 55, null, true),
  ('svm-wednesday-1800', 'san-vicente-mendoza', 'confesion', 'wednesday', '18:00', 40, null, true)
on conflict (id) do update
set
  temple_id = excluded.temple_id,
  type = excluded.type,
  weekday = excluded.weekday,
  start_time = excluded.start_time,
  duration_min = excluded.duration_min,
  notes = excluded.notes,
  is_active = excluded.is_active,
  updated_at = timezone('utc', now());
