create schema if not exists internal;

revoke all on schema internal from public;

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text,
  hierarchy_level smallint not null default 100,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  role_id bigint not null references public.roles(id) on delete cascade,
  app_slug text not null,
  can_access boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  unique (role_id, app_slug)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  avatar_url text,
  role_id bigint not null references public.roles(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id bigint not null references public.roles(id),
  assigned_by uuid references public.profiles(id),
  assigned_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  ip_address text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_permissions_app_slug on public.permissions(app_slug);
create index if not exists idx_profiles_role_id on public.profiles(role_id);
create index if not exists idx_user_roles_user_id on public.user_roles(user_id);
create index if not exists idx_user_roles_role_id on public.user_roles(role_id);
create index if not exists idx_audit_log_user_id on public.audit_log(user_id);
create index if not exists idx_audit_log_created_at on public.audit_log(created_at desc);

create or replace function internal.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row
execute function internal.set_updated_at();

create or replace function internal.is_admin(user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    join public.roles r on r.id = p.role_id
    where p.id = user_id
      and r.slug = 'admin'
  );
$$;

create or replace function internal.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  default_role_id bigint;
  profile_name text;
begin
  select id into default_role_id
  from public.roles
  where slug = 'usuario'
  limit 1;

  if default_role_id is null then
    raise exception 'Role "usuario" is required before creating profiles';
  end if;

  profile_name := coalesce(
    nullif(new.raw_user_meta_data ->> 'name', ''),
    split_part(coalesce(new.email, ''), '@', 1),
    'Usuario'
  );

  insert into public.profiles (id, email, name, role_id)
  values (new.id, coalesce(new.email, ''), profile_name, default_role_id)
  on conflict (id) do update
  set email = excluded.email,
      name = coalesce(excluded.name, public.profiles.name),
      role_id = coalesce(public.profiles.role_id, excluded.role_id),
      updated_at = timezone('utc', now());

  insert into public.user_roles (user_id, role_id, assigned_by)
  values (new.id, default_role_id, null);

  insert into public.audit_log (user_id, action, metadata)
  values (
    new.id,
    'user_created',
    jsonb_build_object('source', 'auth.users_trigger')
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function internal.handle_new_user();

alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists roles_read_authenticated on public.roles;
create policy roles_read_authenticated
on public.roles
for select
to authenticated
using (true);

drop policy if exists roles_manage_admin on public.roles;
create policy roles_manage_admin
on public.roles
for all
to authenticated
using (internal.is_admin(auth.uid()))
with check (internal.is_admin(auth.uid()));

drop policy if exists permissions_read_authenticated on public.permissions;
create policy permissions_read_authenticated
on public.permissions
for select
to authenticated
using (true);

drop policy if exists permissions_manage_admin on public.permissions;
create policy permissions_manage_admin
on public.permissions
for all
to authenticated
using (internal.is_admin(auth.uid()))
with check (internal.is_admin(auth.uid()));

drop policy if exists profiles_read_own_or_admin on public.profiles;
create policy profiles_read_own_or_admin
on public.profiles
for select
to authenticated
using (auth.uid() = id or internal.is_admin(auth.uid()));

drop policy if exists profiles_insert_self_or_admin on public.profiles;
create policy profiles_insert_self_or_admin
on public.profiles
for insert
to authenticated
with check (auth.uid() = id or internal.is_admin(auth.uid()));

drop policy if exists profiles_update_own_or_admin on public.profiles;
create policy profiles_update_own_or_admin
on public.profiles
for update
to authenticated
using (auth.uid() = id or internal.is_admin(auth.uid()))
with check (auth.uid() = id or internal.is_admin(auth.uid()));

drop policy if exists profiles_delete_admin on public.profiles;
create policy profiles_delete_admin
on public.profiles
for delete
to authenticated
using (internal.is_admin(auth.uid()));

drop policy if exists user_roles_read_own_or_admin on public.user_roles;
create policy user_roles_read_own_or_admin
on public.user_roles
for select
to authenticated
using (auth.uid() = user_id or internal.is_admin(auth.uid()));

drop policy if exists user_roles_manage_admin on public.user_roles;
create policy user_roles_manage_admin
on public.user_roles
for insert
to authenticated
with check (internal.is_admin(auth.uid()));

drop policy if exists audit_log_read_own_or_admin on public.audit_log;
create policy audit_log_read_own_or_admin
on public.audit_log
for select
to authenticated
using (auth.uid() = user_id or internal.is_admin(auth.uid()));

drop policy if exists audit_log_insert_own_or_admin on public.audit_log;
create policy audit_log_insert_own_or_admin
on public.audit_log
for insert
to authenticated
with check (auth.uid() = user_id or internal.is_admin(auth.uid()));

grant usage on schema public to anon, authenticated;
grant usage on schema internal to postgres, service_role;

grant select on public.roles to authenticated;
grant select on public.permissions to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.user_roles to authenticated;
grant select, insert on public.audit_log to authenticated;

grant all privileges on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.roles (slug, name, description, hierarchy_level)
values
  ('admin', 'Administrador', 'Control total del ecosistema', 1),
  ('sacerdote', 'Sacerdote', 'Rol pastoral con permisos específicos', 20),
  ('coordinador', 'Coordinador', 'Gestión operativa de servicios y comunidades', 40),
  ('usuario', 'Usuario', 'Acceso básico a aplicaciones autorizadas', 100)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  hierarchy_level = excluded.hierarchy_level;

with role_map as (
  select id, slug from public.roles
),
app_map as (
  select unnest(array['portal', 'biblia', 'calendario', 'usuario']) as app_slug
)
insert into public.permissions (role_id, app_slug, can_access)
select
  r.id,
  a.app_slug,
  case
    when r.slug = 'admin' then true
    when r.slug = 'sacerdote' then a.app_slug in ('portal', 'biblia', 'calendario', 'usuario')
    when r.slug = 'coordinador' then a.app_slug in ('portal', 'calendario', 'usuario')
    when r.slug = 'usuario' then a.app_slug in ('portal', 'biblia', 'calendario')
    else false
  end as can_access
from role_map r
cross join app_map a
on conflict (role_id, app_slug) do update
set can_access = excluded.can_access;

insert into public.profiles (id, email, name, role_id)
select
  u.id,
  coalesce(u.email, ''),
  coalesce(
    nullif(u.raw_user_meta_data ->> 'name', ''),
    split_part(coalesce(u.email, ''), '@', 1),
    'Usuario'
  ),
  (select id from public.roles where slug = 'usuario')
from auth.users u
where not exists (
  select 1 from public.profiles p where p.id = u.id
);
