create extension if not exists pg_trgm;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.biblia_versions (
  code text primary key,
  slug text generated always as (regexp_replace(lower(code), '[^a-z0-9]+', '-', 'g')) stored,
  name text not null,
  abbreviation text,
  language text not null,
  tradition text not null,
  license text not null,
  provider text not null,
  notes text,
  is_enabled boolean not null default false,
  is_internal_only boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists biblia_versions_single_enabled_idx
  on public.biblia_versions ((is_enabled))
  where is_enabled;

create table if not exists public.biblia_books (
  id text primary key,
  version_code text not null references public.biblia_versions(code) on delete cascade,
  slug text not null,
  name text not null,
  position integer not null check (position > 0),
  testament text not null check (testament in ('old', 'new')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (version_code, slug),
  unique (version_code, position)
);

create table if not exists public.biblia_chapters (
  id text primary key,
  version_code text not null references public.biblia_versions(code) on delete cascade,
  book_id text not null references public.biblia_books(id) on delete cascade,
  chapter_number integer not null check (chapter_number > 0),
  verse_count integer not null default 0 check (verse_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (book_id, chapter_number)
);

create table if not exists public.biblia_verses (
  version_code text not null references public.biblia_versions(code) on delete cascade,
  book_id text not null references public.biblia_books(id) on delete cascade,
  chapter_id text not null references public.biblia_chapters(id) on delete cascade,
  chapter_number integer not null check (chapter_number > 0),
  verse_number integer not null check (verse_number > 0),
  verse_text text not null check (length(trim(verse_text)) > 0),
  search_vector tsvector generated always as (to_tsvector('spanish', coalesce(verse_text, ''))) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (chapter_id, verse_number)
);

create index if not exists biblia_verses_book_chapter_idx
  on public.biblia_verses(book_id, chapter_number, verse_number);

create index if not exists biblia_verses_search_idx
  on public.biblia_verses using gin(search_vector);

create index if not exists biblia_verses_trgm_idx
  on public.biblia_verses using gin(verse_text gin_trgm_ops);

create table if not exists public.liturgy_daily_readings (
  id bigint generated by default as identity primary key,
  reading_date date not null,
  rite text not null,
  region_code text not null,
  celebration_type text,
  celebration_name text,
  cycle text,
  week integer,
  first_reading_ref text,
  psalm_ref text,
  second_reading_ref text,
  gospel_ref text,
  source_year integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (reading_date, rite, region_code),
  check (rite = 'roman'),
  check (region_code = 'AR')
);

create table if not exists public.biblia_ingestion_runs (
  id bigint generated by default as identity primary key,
  source_name text not null,
  run_status text not null check (run_status in ('running', 'success', 'failed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  records_processed integer,
  error_summary text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_updated_at_biblia_versions on public.biblia_versions;
create trigger set_updated_at_biblia_versions
before update on public.biblia_versions
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_biblia_books on public.biblia_books;
create trigger set_updated_at_biblia_books
before update on public.biblia_books
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_biblia_chapters on public.biblia_chapters;
create trigger set_updated_at_biblia_chapters
before update on public.biblia_chapters
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_biblia_verses on public.biblia_verses;
create trigger set_updated_at_biblia_verses
before update on public.biblia_verses
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_liturgy_daily_readings on public.liturgy_daily_readings;
create trigger set_updated_at_liturgy_daily_readings
before update on public.liturgy_daily_readings
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_biblia_ingestion_runs on public.biblia_ingestion_runs;
create trigger set_updated_at_biblia_ingestion_runs
before update on public.biblia_ingestion_runs
for each row execute procedure public.set_updated_at();

alter table public.biblia_versions enable row level security;
alter table public.biblia_books enable row level security;
alter table public.biblia_chapters enable row level security;
alter table public.biblia_verses enable row level security;
alter table public.liturgy_daily_readings enable row level security;
alter table public.biblia_ingestion_runs enable row level security;
