import type {
  CelebrationRecord,
  CelebrationType,
  TempleRecord,
  Weekday,
} from "@/types/horarios";

function celebration(
  id: string,
  templeId: string,
  type: CelebrationType,
  weekday: Weekday,
  startTime: string,
  durationMin: number,
  notes?: string,
): CelebrationRecord {
  return {
    id,
    templeId,
    type,
    weekday,
    startTime,
    durationMin,
    notes,
  };
}

export const TEMPLES: TempleRecord[] = [
  {
    id: "santa-teresita-parana",
    name: "Parroquia Santa Teresita",
    city: "Parana",
    province: "Entre Rios",
    address: "Av. Almafuerte 420, Parana",
    lat: -31.7424,
    lng: -60.5238,
    status: "updated",
    contactPhone: "+54 343 412-0045",
    contactWhatsApp: "+54 343 470-8954",
    notes: "Confesiones 30 minutos antes de Misa vespertina.",
  },
  {
    id: "catedral-parana",
    name: "Catedral Nuestra Senora del Rosario",
    city: "Parana",
    province: "Entre Rios",
    address: "Su Santidad Francisco 57, Parana",
    lat: -31.7317,
    lng: -60.5235,
    status: "updated",
    contactPhone: "+54 343 423-0181",
    notes: "Misa dominical central con coro arquidiocesano.",
  },
  {
    id: "sagrado-corazon-parana",
    name: "Capilla Sagrado Corazon",
    city: "Parana",
    province: "Entre Rios",
    address: "Calle Nogoya 1330, Parana",
    lat: -31.7481,
    lng: -60.5077,
    status: "review",
    contactPhone: "+54 343 421-5531",
    notes: "Horario sujeto a confirmacion semanal.",
  },
  {
    id: "san-jose-orero-sfe",
    name: "Parroquia San Jose Obrero",
    city: "Santa Fe",
    province: "Santa Fe",
    address: "J. M. Zuviria 3050, Santa Fe",
    lat: -31.6408,
    lng: -60.7001,
    status: "updated",
    contactPhone: "+54 342 456-0021",
  },
  {
    id: "basilica-guadalupe-sfe",
    name: "Basilica de Guadalupe",
    city: "Santa Fe",
    province: "Santa Fe",
    address: "Javier de la Rosa 623, Santa Fe",
    lat: -31.6132,
    lng: -60.6729,
    status: "updated",
    contactPhone: "+54 342 460-1111",
  },
  {
    id: "san-miguel-cordoba",
    name: "Parroquia San Miguel Arcangel",
    city: "Cordoba",
    province: "Cordoba",
    address: "Av. Colon 812, Cordoba",
    lat: -31.4166,
    lng: -64.1888,
    status: "stale",
    contactPhone: "+54 351 434-2200",
    notes: "Ultima actualizacion reportada hace mas de 30 dias.",
  },
  {
    id: "santa-rita-cordoba",
    name: "Parroquia Santa Rita",
    city: "Cordoba",
    province: "Cordoba",
    address: "Juan B. Justo 2470, Cordoba",
    lat: -31.4014,
    lng: -64.1674,
    status: "review",
    contactPhone: "+54 351 475-9090",
  },
  {
    id: "nuestra-senora-pilar-rosario",
    name: "Parroquia Nuestra Senora del Pilar",
    city: "Rosario",
    province: "Santa Fe",
    address: "Cordoba 1420, Rosario",
    lat: -32.9478,
    lng: -60.6393,
    status: "updated",
    contactPhone: "+54 341 429-7155",
  },
  {
    id: "san-cayetano-rosario",
    name: "Parroquia San Cayetano",
    city: "Rosario",
    province: "Santa Fe",
    address: "Buenos Aires 2150, Rosario",
    lat: -32.9608,
    lng: -60.6428,
    status: "updated",
    contactPhone: "+54 341 486-4450",
  },
  {
    id: "cristo-redentor-buenos-aires",
    name: "Parroquia Cristo Redentor",
    city: "Buenos Aires",
    province: "Buenos Aires",
    address: "Av. Rivadavia 4800, CABA",
    lat: -34.6155,
    lng: -58.4328,
    status: "review",
    contactPhone: "+54 11 4124-8800",
  },
  {
    id: "san-benito-buenos-aires",
    name: "Parroquia San Benito Abad",
    city: "Buenos Aires",
    province: "Buenos Aires",
    address: "Maure 920, CABA",
    lat: -34.5741,
    lng: -58.4381,
    status: "updated",
    contactPhone: "+54 11 4777-7397",
  },
  {
    id: "san-vicente-mendoza",
    name: "Parroquia San Vicente Ferrer",
    city: "Mendoza",
    province: "Mendoza",
    address: "Belgrano 240, Mendoza",
    lat: -32.8898,
    lng: -68.8454,
    status: "stale",
    contactPhone: "+54 261 423-7720",
  },
];

export const CELEBRATIONS: CelebrationRecord[] = [
  celebration(
    "stp-monday-1900",
    "santa-teresita-parana",
    "misa",
    "monday",
    "19:00",
    50,
  ),
  celebration(
    "stp-tuesday-1900",
    "santa-teresita-parana",
    "misa",
    "tuesday",
    "19:00",
    50,
  ),
  celebration(
    "stp-wednesday-1900",
    "santa-teresita-parana",
    "misa",
    "wednesday",
    "19:00",
    50,
  ),
  celebration(
    "stp-thursday-1900",
    "santa-teresita-parana",
    "misa",
    "thursday",
    "19:00",
    50,
  ),
  celebration(
    "stp-friday-1900",
    "santa-teresita-parana",
    "misa",
    "friday",
    "19:00",
    50,
  ),
  celebration(
    "stp-saturday-1930",
    "santa-teresita-parana",
    "misa",
    "saturday",
    "19:30",
    55,
  ),
  celebration(
    "stp-sunday-0930",
    "santa-teresita-parana",
    "misa",
    "sunday",
    "09:30",
    60,
  ),
  celebration(
    "stp-sunday-2000",
    "santa-teresita-parana",
    "misa",
    "sunday",
    "20:00",
    60,
  ),
  celebration(
    "stp-thursday-1800",
    "santa-teresita-parana",
    "adoracion",
    "thursday",
    "18:00",
    45,
  ),
  celebration(
    "stp-saturday-1830",
    "santa-teresita-parana",
    "confesion",
    "saturday",
    "18:30",
    40,
  ),
  celebration(
    "cat-monday-1830",
    "catedral-parana",
    "misa",
    "monday",
    "18:30",
    50,
  ),
  celebration(
    "cat-tuesday-1830",
    "catedral-parana",
    "misa",
    "tuesday",
    "18:30",
    50,
  ),
  celebration(
    "cat-wednesday-1830",
    "catedral-parana",
    "misa",
    "wednesday",
    "18:30",
    50,
  ),
  celebration(
    "cat-thursday-1830",
    "catedral-parana",
    "misa",
    "thursday",
    "18:30",
    50,
  ),
  celebration(
    "cat-friday-1830",
    "catedral-parana",
    "misa",
    "friday",
    "18:30",
    50,
  ),
  celebration(
    "cat-sunday-1030",
    "catedral-parana",
    "misa",
    "sunday",
    "10:30",
    65,
  ),
  celebration(
    "cat-sunday-1900",
    "catedral-parana",
    "misa",
    "sunday",
    "19:00",
    65,
  ),
  celebration(
    "scr-sunday-1100",
    "sagrado-corazon-parana",
    "misa",
    "sunday",
    "11:00",
    55,
  ),
  celebration(
    "scr-friday-1800",
    "sagrado-corazon-parana",
    "rosario",
    "friday",
    "18:00",
    35,
  ),
  celebration(
    "sjo-monday-1900",
    "san-jose-orero-sfe",
    "misa",
    "monday",
    "19:00",
    55,
  ),
  celebration(
    "sjo-tuesday-1900",
    "san-jose-orero-sfe",
    "misa",
    "tuesday",
    "19:00",
    55,
  ),
  celebration(
    "sjo-wednesday-1900",
    "san-jose-orero-sfe",
    "misa",
    "wednesday",
    "19:00",
    55,
  ),
  celebration(
    "sjo-thursday-1900",
    "san-jose-orero-sfe",
    "misa",
    "thursday",
    "19:00",
    55,
  ),
  celebration(
    "sjo-friday-1900",
    "san-jose-orero-sfe",
    "misa",
    "friday",
    "19:00",
    55,
  ),
  celebration(
    "sjo-saturday-1930",
    "san-jose-orero-sfe",
    "misa",
    "saturday",
    "19:30",
    60,
  ),
  celebration(
    "sjo-sunday-0900",
    "san-jose-orero-sfe",
    "misa",
    "sunday",
    "09:00",
    65,
  ),
  celebration(
    "sjo-sunday-2000",
    "san-jose-orero-sfe",
    "misa",
    "sunday",
    "20:00",
    65,
  ),
  celebration(
    "bgs-sunday-1030",
    "basilica-guadalupe-sfe",
    "misa",
    "sunday",
    "10:30",
    65,
  ),
  celebration(
    "bgs-sunday-1900",
    "basilica-guadalupe-sfe",
    "misa",
    "sunday",
    "19:00",
    65,
  ),
  celebration(
    "bgs-saturday-1730",
    "basilica-guadalupe-sfe",
    "confesion",
    "saturday",
    "17:30",
    45,
  ),
  celebration(
    "smc-sunday-1100",
    "san-miguel-cordoba",
    "misa",
    "sunday",
    "11:00",
    55,
  ),
  celebration(
    "smc-wednesday-1930",
    "san-miguel-cordoba",
    "misa",
    "wednesday",
    "19:30",
    55,
  ),
  celebration(
    "srt-sunday-0930",
    "santa-rita-cordoba",
    "misa",
    "sunday",
    "09:30",
    55,
  ),
  celebration(
    "srt-sunday-1930",
    "santa-rita-cordoba",
    "misa",
    "sunday",
    "19:30",
    55,
  ),
  celebration(
    "srt-thursday-1800",
    "santa-rita-cordoba",
    "adoracion",
    "thursday",
    "18:00",
    45,
  ),
  celebration(
    "nsp-monday-1900",
    "nuestra-senora-pilar-rosario",
    "misa",
    "monday",
    "19:00",
    50,
  ),
  celebration(
    "nsp-tuesday-1900",
    "nuestra-senora-pilar-rosario",
    "misa",
    "tuesday",
    "19:00",
    50,
  ),
  celebration(
    "nsp-wednesday-1900",
    "nuestra-senora-pilar-rosario",
    "misa",
    "wednesday",
    "19:00",
    50,
  ),
  celebration(
    "nsp-thursday-1900",
    "nuestra-senora-pilar-rosario",
    "misa",
    "thursday",
    "19:00",
    50,
  ),
  celebration(
    "nsp-friday-1900",
    "nuestra-senora-pilar-rosario",
    "misa",
    "friday",
    "19:00",
    50,
  ),
  celebration(
    "nsp-sunday-1000",
    "nuestra-senora-pilar-rosario",
    "misa",
    "sunday",
    "10:00",
    60,
  ),
  celebration(
    "nsp-sunday-2000",
    "nuestra-senora-pilar-rosario",
    "misa",
    "sunday",
    "20:00",
    60,
  ),
  celebration(
    "sca-saturday-1900",
    "san-cayetano-rosario",
    "misa",
    "saturday",
    "19:00",
    55,
  ),
  celebration(
    "sca-sunday-1030",
    "san-cayetano-rosario",
    "misa",
    "sunday",
    "10:30",
    60,
  ),
  celebration(
    "sca-friday-1830",
    "san-cayetano-rosario",
    "rosario",
    "friday",
    "18:30",
    35,
  ),
  celebration(
    "crb-sunday-1100",
    "cristo-redentor-buenos-aires",
    "misa",
    "sunday",
    "11:00",
    60,
  ),
  celebration(
    "crb-sunday-2000",
    "cristo-redentor-buenos-aires",
    "misa",
    "sunday",
    "20:00",
    60,
  ),
  celebration(
    "crb-thursday-1830",
    "cristo-redentor-buenos-aires",
    "liturgia",
    "thursday",
    "18:30",
    45,
  ),
  celebration(
    "sbb-monday-1830",
    "san-benito-buenos-aires",
    "misa",
    "monday",
    "18:30",
    50,
  ),
  celebration(
    "sbb-tuesday-1830",
    "san-benito-buenos-aires",
    "misa",
    "tuesday",
    "18:30",
    50,
  ),
  celebration(
    "sbb-wednesday-1830",
    "san-benito-buenos-aires",
    "misa",
    "wednesday",
    "18:30",
    50,
  ),
  celebration(
    "sbb-thursday-1830",
    "san-benito-buenos-aires",
    "misa",
    "thursday",
    "18:30",
    50,
  ),
  celebration(
    "sbb-friday-1830",
    "san-benito-buenos-aires",
    "misa",
    "friday",
    "18:30",
    50,
  ),
  celebration(
    "sbb-sunday-1000",
    "san-benito-buenos-aires",
    "misa",
    "sunday",
    "10:00",
    60,
  ),
  celebration(
    "sbb-sunday-1900",
    "san-benito-buenos-aires",
    "misa",
    "sunday",
    "19:00",
    60,
  ),
  celebration(
    "svm-sunday-0930",
    "san-vicente-mendoza",
    "misa",
    "sunday",
    "09:30",
    55,
  ),
  celebration(
    "svm-sunday-1930",
    "san-vicente-mendoza",
    "misa",
    "sunday",
    "19:30",
    55,
  ),
  celebration(
    "svm-wednesday-1800",
    "san-vicente-mendoza",
    "confesion",
    "wednesday",
    "18:00",
    40,
  ),
];
